library(readr)
library(dplyr)
library(party)
library(rpart)
library(rpart.plot)
library(ROCR)
set.seed(100)
titanic3 <- "https://goo.gl/At238b" %>% read.csv %>% select(survived,embarked, sex, sibsp, parch, fare) %>% mutate(embarked = factor(embarked), sex = factor(sex))
str(titanic3)
head(titanic3)
.data <- c("training", "test") %>% sample(nrow(titanic3), replace = T) %>% split(titanic3, .)
rtree_fit <- rpart(survived ~ ., .data$training) 
rpart.plot(rtree_fit)
tree <- rpart(survived ~ ., data = titanic3, method = "class")
pred <- predict(tree, titanic3, type="class")
table(titanic3$survived, pred)
PredictionPositive <- c(212, 53)
PredictionNegative <- c(78,371)
conf <- data.frame(PredictionPositive, PredictionNegative)
conf