install.packages("effects")
library(effects)
head(Cowles)
mod.cowles <- glm(volunteer ~ sex + neuroticism*extraversion, data = Cowles, family=binomial)
summary(mod.cowles)
plot(allEffects(mod.cowles))
e.out <- allEffects(mod.cowles)
e.out$sex$model.matrix
mean(Cowles$neuroticism)
mean(Cowles$extraversion)
mean(Cowles$neuroticism) * mean(Cowles$extraversion)
invLogit <- function(x) exp(x)/(1 + exp(x))
invLogit(e.out$sex$model.matrix %*% coef(mod.cowles))
ndata <- data.frame(sex=factor(c("female","male")),neuroticism=11.47009, extraversion=12.37298)
predict(object = mod.cowles, newdata = ndata, type = "response")
plot(allEffects(mod.cowles, typical=median))
allEffects(mod.cowles)
head(e.out$`neuroticism:extraversion`$model.matrix)
prop.table(table(Cowles$sex))
plot(allEffects(mod.cowles, xlevels=list(extraversion=seq(10, 20, 2), neuroticism=10:20), given.values=c(sexmale=1)))
plot(Effect(focal.predictors = c("neuroticism","extraversion","sex"), mod = mod.cowles, xlevels=list(extraversion=seq(10, 20, 2), neuroticism=10:20)))
plot(Effect(focal.predictors = c("neuroticism","extraversion","sex"), mod = mod.cowles, xlevels=list(extraversion=seq(10, 20, 2), neuroticism=10:20)),multiline = TRUE)
